# This workflows will upload a Python Package using Twine when a release is created
# For more information see: https://help.github.com/en/actions/language-and-framework-guides/using-python-with-github-actions#publishing-to-package-registries

# Note: the first change per day is used to build daily/night release.
# Therefore, merging one PR per day is recommended. Otherwise, the we need to manually trigger the CI later.

name: Upload Python Package

on:
  workflow_dispatch:
  schedule:
    - cron: "59 8 * * *"

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master
      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: "3.12"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install setuptools wheel packaging
          pip install openmim==0.3.9
          python -m ensurepip --upgrade
          python -m pip install --upgrade setuptools
      - name: Build wheel
        run: |
          for v in common core features tabular multimodal timeseries autogluon
          do
            cd "$v"/
            python setup.py sdist bdist_wheel --dist-dir=../dist  --bdist-dir=../dist2
            cd ..
          done
      - name: Upload wheel to GitHub Releases
        uses: ncipollo/release-action@v1
        with:
          artifacts: "dist/*.whl"
          token: ${{ secrets.GITHUB_TOKEN }}